describe('Desafio automação', () => {
    it('Acessar site com sucesso e preencher o formulário', () => {
        cy.visit('https://demoqa.com/')
        cy.get('.card-body').eq(1).click()
        cy.get('li#item-0').eq(1).click()
        cy.get('#firstName').type('teste')
        cy.get('#lastName').type('teste')
        cy.get('#userEmail').type('voce@pode.com')
        cy.get('#gender-radio-1').check({ force: true })
        cy.get('#gender-radio-1').should('be.checked')
        cy.get('#userNumber').type('1234564784')
        cy.get('#dateOfBirthInput').click()
        cy.get('.react-datepicker__year-select').select('2000')
        cy.get('.react-datepicker__month-select').select('February')
        cy.get('.react-datepicker__day--015').click()
        cy.get('.subjects-auto-complete__value-container').type('Arts{enter}')
        cy.get('#hobbies-checkbox-1').check({ force: true })
        cy.get('#hobbies-checkbox-1').should('be.checked')
        cy.get('#hobbies-checkbox-2').check({ force: true })
        cy.get('#hobbies-checkbox-2').should('be.checked')
        cy.get('#hobbies-checkbox-3').check({ force: true })
        cy.get('#hobbies-checkbox-3').should('be.checked')
        cy.get('#uploadPicture').attachFile('testeace.txt')
        cy.get('#currentAddress').type('cypress')
        cy.get('#state').click()
        cy.contains('.css-yt9ioa-option', 'Uttar Pradesh').click()
        cy.contains('.css-1wa3eu0-placeholder', 'Se').click()
        cy.get('.css-1hwfws3').eq(1).click()
        cy.get('.css-tlfecz-indicatorContainer').eq(1).click()
        cy.get('#react-select-4-input').type('Agra{enter}')
        cy.get('#submit').click()
        cy.get('#example-modal-sizes-title-lg')
          .should('be.visible')
          .should('have.text', 'Thanks for submitting the form')
        cy.get('#closeLargeModal').click({ force: true })
    })
})

